### PR TITLE
Add a basic configuration for TravisCI

### PR DESCRIPTION
**Pull request by jrha**

### CODE REVIEW

**Comment by jrha** [comment]
💚

**Comment by jrha** [comment]
I'm unsure whether also adding `make install` `make installcheck` to the test script would be useful.

**Comment by stdweird** [comment]
any reason not to add them? if they cause to many false positives, we can always comment it out

**Comment by jrha** [comment]
I don't think it has any benefit, it just runs the tests in a different location, but sure.

**Comment by jrha** [comment]
@stdweird done

**Pull request merged**
